### PR TITLE
Fixing nuget references

### PR DESCRIPTION
**Pull request by Macaddict42**
No bugfixes but nuget packages never work straight out of a clone so hopefully this should fix it

### CODE REVIEW

**Comment by zaafar** [comment]
Works fine if you load plugin project within poehud project. That way you can run the plugin in debug mode and debug the plugin step by step.

**Comment by Arecurius0** [comment]
@zaafar could you give a little step by step guide how i do that when i have PoeHud project open in Visual Studio ?

**Comment by zaafar** [comment]
https://docs.microsoft.com/en-us/sql/ssms/solution/add-an-existing-project-to-a-solution?view=sql-server-2017

Let me know if that does not work for you.

**Comment by Arecurius0** [comment]
I followed the steps in the link and added plugin to the PoeHud Project in Visual Studio but when trying to build the Solution or building only the plugin i get 66 Errors as the result of missing references.

**Pull request closed without merging**
